# Generated by Django 4.2.7 on 2023-11-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('atracoes', models.ManyToManyField(to='atracoes.atracao')),
                ('avaliacoes', models.ManyToManyField(to='avaliacoes.avaliacao')),
                ('comentarios', models.ManyToManyField(to='comentarios.comentario')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
    ]
